= Image promotion using ConfigMaps in OpenShift 3
In this example, we're demonstrating how to promote images from environment to environment.
While doing this promotion, we're using the same DeploymentConfiguration as we have all the Configuration required for the app externalized into a ConfigMap.
The same ConfigMap is deployed in every environment, but with different values for the configuration

== How to run
In the examples folder, there is a ./load-all.sh script that will set up everything for you

There will be 2 projects. In this example a project will resemble a stage/environment for the given application:

- node-app-dev
- node-app-test

Both will have a node.js application that will show some details, and a value defined in the ConfigMap that will be relative for each and every project (environment)

== How to promote the application from dev to test
Just tag the image doing:

----
oc tag node-app-dev/node-app:latest node-app-test/node-app:test
----

You'll see how the application get deployed into the test environment.
